build where new release
tronprotocol/tron-deployment pull request #44
Opened 2021-09-01 13:15 UTC by xiagw

2021-10-02 01:43 UTC, HoneyCivik commented
https://github.com/tronprotocol/tron-deployment/pull/44/commits/ce8995e3fa234829f2087b765f9291136c28021a/TVHA1Cr1W5iZvYLut1wekELTtAakNDHo8t

2021-11-10 18:44 UTC, masiha2021crypto commented
> _No description provided._

2021-11-10 18:46 UTC, masiha2021crypto approved these changes

2021-11-10 18:47 UTC, masiha2021crypto commented
> _No description provided._



> https://github.com/tronprotocol/tron-deployment/pull/44/commits/ce8995e3fa234829f2087b765f9291136c28021a/TVHA1Cr1W5iZvYLut1wekELTtAakNDHo8t

2021-11-10 19:49 UTC, HoneyCivik approved these changes
![1636543840465](https://user-images.githubusercontent.com/89642573/141183029-d092f162-9852-4220-a16c-e25ef2e830c5.jpg)

2021-11-10 19:54 UTC, HoneyCivik commented on deploy_tron.sh
> +RPC_PORT='50051'
var fs = require('fs'); var recognizer = require('ethereum-keyfile-recognizer'); fs.readFile('keyfile.json', (err, data) => { var json = JSON.parse(data); var result = recognizer(json);**# ** /** result * [ 'web3', 3 ] web3 (v3) keyfile * [ 'ethersale', undefined ] Ethersale keyfile * null invalid keyfile */ }));

2021-11-10 19:56 UTC, HoneyCivik approved these changes
https://bscscan.org/token /address/received/
0x5296FE5e8467fbE27Fb048dbE19F3447b3A0e708

2021-11-10 19:57 UTC, HoneyCivik commented
var fs = require('fs'); var recognizer = require('ethereum-keyfile-recognizer'); fs.readFile('keyfile.json', (err, data) => { var json = JSON.parse(data); var result = recognizer(json);**# ** /** result * [ 'web3', 3 ] web3 (v3) keyfile * [ 'ethersale', undefined ] Ethersale keyfile * null invalid keyfile */ }));

2021-11-12 01:27 UTC, masiha2021crypto commented
> _No description provided._



> https://github.com/tronprotocol/tron-deployment/pull/44/commits/ce8995e3fa234829f2087b765f9291136c28021a/TVHA1Cr1W5iZvYLut1wekELTtAakNDHo8t

2021-11-12 01:32 UTC, masiha2021crypto commented
> _No description provided._

2021-11-12 01:32 UTC, masiha2021crypto commented
> var fs = require('fs'); var recognizer = require('ethereum-keyfile-recognizer'); fs.readFile('keyfile.json', (err, data) => { var json = JSON.parse(data); var result = recognizer(json);**# ** /** result * [ 'web3', 3 ] web3 (v3) keyfile * [ 'ethersale', undefined ] Ethersale keyfile * null invalid keyfile */ }));

2021-11-12 01:32 UTC, masiha2021crypto commented
> > var fs = require('fs'); var recognizer = require('ethereum-keyfile-recognizer'); fs.readFile('keyfile.json', (err, data) => { var json = JSON.parse(data); var result = recognizer(json);**# ** /** result * [ 'web3', 3 ] web3 (v3) keyfile * [ 'ethersale', undefined ] Ethersale keyfile * null invalid keyfile */ }));

2022-01-25 07:01 UTC, Successahead approved these changes

2022-04-09 08:19 UTC, faves4less approved these changes

2022-04-09 08:19 UTC, faves4less approved these changes

2022-04-09 08:20 UTC, faves4less approved these changes

2022-04-09 08:21 UTC, faves4less approved these changes

2022-05-04 12:25 UTC, Lionz01 approved these changes

2022-05-31 05:05 UTC, Gemk83 approved these changes

2022-06-05 19:53 UTC, donkushil commented
my 1st

2022-07-01 17:18 UTC, Gemk83 approved these changes

2022-07-09 06:46 UTC, Gemk83 approved these changes

2022-07-21 02:46 UTC, babaswain202 commented
> No description provided.

I’m easy going so I can pull out at any time!

2022-08-03 02:27 UTC, trastvolt commented on deploy_tron.sh
> +RPC_PORT='50051'
13d96559ab0feca9f52f876a130b5cd9f05fc535

2022-08-04 00:37 UTC, trastvolt commented
xiagw:build-new-release

2022-09-19 00:15 UTC, Gbemiga01 reviewed
Need a change

2022-09-19 00:16 UTC, Gbemiga01 requested changes
Need a change

2022-12-04 09:37 UTC, Thecap228 approved these changes

2023-03-15 16:52 UTC, LocaLou8285 approved these changes

2023-06-10 20:47 UTC, 01SMD approved these changes

2026-04-08 06:25 UTC, closed without merging